### ISSUE TITLE
准备入坑小白求指教

### ISSUE THREAD

**Issue by tlerbao** [josways/B460M-MORTAR#10]
> 实在等不及iMac跟新配置了，双十一准备先入坑黑果，自己写了下面配置以及问题求教。

### 拟定配置

CPU：I5 10400								
主板：MSI B460M Mortar												1939元/套
显卡：蓝宝石RX 590 GME 8G D5									1599元
内存：金士顿(Kingston) DDR4 2666 16GB(8G×2)		499元
硬盘：WD Blue SN550 1TB												789元
电源：酷冷至尊 650W GX650											469元
机箱：预算500左右待定													500元
蓝牙：BCM94360CD														256元
散热：利民 FS140																259元

Q1：MSI B460M Mortar	这主板直接可以插显卡和无线网卡吧，不用转接吧？
Q2：有没有必要必须上ATX主板和机箱？
Q3：10400有没有搭配的比较完美黑果的EFI的ATX主板型号推荐？
Q4：机箱有高颜值推荐吗？无需侧透和各种RGB
Q5：我以后可能使用有线网络，那么装的BCM94360网卡就是为蓝牙而生的是吧？可以混用是吧？
Q6：显卡是RX590还是5500XT？
Q7：以上所有配置请尽情吐槽，我不是土豪，能帮我省钱就太感谢了

**Comment by blueskies2099** [comment]
a1: 可以直接插，么得问题，两个 pcie x16 一个 pcie x1
a2: 没必要 MATX挺舒服的 
a3: 不知，微星这个迫击炮挺稳的，我用了库主的这套，直接安装很稳
a4: 高颜值？ 你喜欢大的还是小的？ 太宽泛了
a5: 蓝牙无线都免驱，可以混用，无线关了就是
a6: 买新不买旧？
a7: 那我就说喽，大兄弟的板u套装怎么是1939一套，我在拼多多 1684买的。拼多多，品牌黑卡了解一下，ddr4 3200 英睿达双8只需405（品牌黑卡前提下）。机箱的话，淘宝上有很多小作坊，还行吧，乔思伯的可以看下做工挺不错的。
**题外话**：没有给拼多多打广告，是拼多多真的要便宜很多，记得品牌黑卡哦。

**Comment by tlerbao** [comment]
@wangqingzh 
Q1：ddr4 3200 英睿达双8只需405 ? 这个迫击炮主板最多只能2666频率内存吧？
Q2：有不少人推荐Asgard和酷兽的内存，16x2才500多，貌似很划算？
Q3：重要：必须要装蓝牙无线网卡才能实现隔空投送、随航、接力等功能是吧，板载网卡插网线上网+蓝牙适配器是做不到的是吧？
Q4：机箱目前就MATX规格的选一个吧，爱国者YOGO M2好像还凑活，其实我想买非侧透的，年纪大了，不喜欢太浮夸的RGB哈。
Q5：如果能介绍一下购买经验最好了，不知道哪里买便宜，比如什么能在拼多多买更划算，什么在淘宝买更划算，什么在京东买更划算哈哈。


万分感谢百忙之中抽空回答。

**Comment by josways** [comment]
> > 实在等不及iMac跟新配置了，双十一准备先入坑黑果，自己写了下面配置以及问题求教。
> 
> ### 拟定配置
> CPU：I5 10400
> 主板：MSI B460M Mortar 1939元/套
> 显卡：蓝宝石RX 590 GME 8G D5 1599元
> 内存：金士顿(Kingston) DDR4 2666 16GB(8G×2) 499元
> 硬盘：WD Blue SN550 1TB 789元
> 电源：酷冷至尊 650W GX650 469元
> 机箱：预算500左右待定 500元
> 蓝牙：BCM94360CD 256元
> 散热：利民 FS140 259元
> 
> Q1：MSI B460M Mortar 这主板直接可以插显卡和无线网卡吧，不用转接吧？
> Q2：有没有必要必须上ATX主板和机箱？
> Q3：10400有没有搭配的比较完美黑果的EFI的ATX主板型号推荐？
> Q4：机箱有高颜值推荐吗？无需侧透和各种RGB
> Q5：我以后可能使用有线网络，那么装的BCM94360网卡就是为蓝牙而生的是吧？可以混用是吧？
> Q6：显卡是RX590还是5500XT？
> Q7：以上所有配置请尽情吐槽，我不是土豪，能帮我省钱就太感谢了

A1:  无线网卡需要转接板。淘宝可以买到。苹果的接口 转 pcie x1 。
A2:  看个人的拓展需求。
A3:  可以自己再Github进行检索。
A4 : 有钱随便买 没钱 屌丝伯 
A5:  可以混用，无线网卡的意义就是 支持 接力 隔空投送 随行 。 如果没有其它苹果设备 可以不装无线网卡。
A6:  没用过xt系列。
A7:  随便买。

**Comment by blueskies2099** [comment]
@tlerbao 
a1: 是的拼多多品牌黑卡可以减去十几块，迫击炮只能2666，我随便买的，当时也没注意，不过2666也没便宜多少吧
a2: 这个就不清楚了，买内存主要还是看颗粒吧，16x2 500多有点香，，，我才知道，不然就去买这个，，，，
a3: 这些功能我没用过，不知。。。我就是浏览器+ide+聊天软件
a4: 我买的 小喆b3 368 14L 主要看中小吧 电源是 sfx 电源 有侧透没光 我之前用过 乔思伯 c3 plus 挺好的 乔思伯你可以看下 我挺喜欢乔思伯的 买这个机箱就是图小 乔思伯没我想要的合适的 其他的 加钱总有你想要的/斜眼笑
a5：京东的话价格稍贵一点，其实天猫的价格跟京东差不多，我电源和显卡在京东买的，毕竟这俩玩意怕炸，其他的建议拼多多吧，淘宝越来越狗了，拼多多的活动比较多。反正，cpu、内存、固态几乎都不会坏。

**Comment by blueskies2099** [comment]
@josways 
迫击炮 可以直接插 无线网卡啊 我插的 pcie 无线网卡

**Comment by tlerbao** [comment]
@wangqingzh 嗯 据说网上的带天线的网卡也是他们后改装的用苹果的拆机卡加上蓝牙模块和座子，直接买这种就直接插pcie接口了。

**Comment by josways** [comment]
> @wangqingzh
> Q1：ddr4 3200 英睿达双8只需405 ? 这个迫击炮主板最多只能2666频率内存吧？
> Q2：有不少人推荐Asgard和酷兽的内存，16x2才500多，貌似很划算？
> Q3：重要：必须要装蓝牙无线网卡才能实现隔空投送、随航、接力等功能是吧，板载网卡插网线上网+蓝牙适配器是做不到的是吧？
> Q4：机箱目前就MATX规格的选一个吧，爱国者YOGO M2好像还凑活，其实我想买非侧透的，年纪大了，不喜欢太浮夸的RGB哈。
> Q5：如果能介绍一下购买经验最好了，不知道哪里买便宜，比如什么能在拼多多买更划算，什么在淘宝买更划算，什么在京东买更划算哈哈。
> 
> 万分感谢百忙之中抽空回答。

A1:  10400 买 2666  ， 10700 买 3000。
A2: 我自己用酷兽 16G 2666 *4 , 以及玖合 16G 2666 *4 ，以及 英睿达 8G 3200 *4
A3: 随航 隔空投送 是必须， 接力不确定。
A4: 可以买 屌丝伯 。 淘宝有非侧透版本。
A5: 随便买。

**Comment by tlerbao** [comment]
@josways 我没明白限制内存频率的到底是cpu还是主板，同样是用b460m 迫击炮，用10400和10700分别可以上2666和3000频率？

**Comment by blueskies2099** [comment]
@tlerbao cpu 你下个app cpu-l 可以看 cpu 参数

**Comment by josways** [comment]
> @josways 我没明白限制内存频率的到底是cpu还是主板，同样是用b460m 迫击炮，用10400和10700分别可以上2666和3000频率？
迫击炮这款主板 内存频率跟着 CPU。
10400 CPU 支持 2666 
10700 及以上 支持 2933

**Comment by blueskies2099** [comment]
[https://apkpure.com/cn/cpu-l/com.ijsoft.cpul](url)

**Comment by tlerbao** [comment]
@josways @wangqingzh 两位有没有推荐的比较划算靠谱的店铺

**Comment by blueskies2099** [comment]
@tlerbao 么得 我纯粹瞎买 看到谁便宜买谁的 显卡和电源 我小心一点 在京东买的

**Comment by josways** [comment]
> @josways @wangqingzh 两位有没有推荐的比较划算靠谱的店铺

无 我是加强党 建议京东一步到位，内存插满 固态插满。

**Comment by blueskies2099** [comment]
@josways 骚气 我也想加满内存 下个月发工资 搞起来

**Comment by tlerbao** [comment]
@josways @wangqingzh 固态是 SN750 还是SN550

**Comment by blueskies2099** [comment]
@tlerbao 我买的 sn750

**Comment by blueskies2099** [comment]
@tlerbao 别买981就完事了

**Comment by tlerbao** [comment]
@josways @wangqingzh 240水冷能不能压住10700

**Comment by josways** [comment]
> @josways @wangqingzh 240水冷能不能压住10700

按最大功耗300W ， 一般满载在 150W 左右。

**Comment by blueskies2099** [comment]
@tlerbao 不超过100度 都不是事儿

**Comment by blueskies2099** [comment]
不要想太多 买来就草 这些东西挺能草的

**Comment by tlerbao** [comment]
下面这两个好像都行哈哈
![image](https://user-images.githubusercontent.com/20442232/96336252-07243000-10b1-11eb-81cf-5d90f8368cae.png)
![image](https://user-images.githubusercontent.com/20442232/96336255-11462e80-10b1-11eb-8023-0d027dd366ca.png)

**Comment by josways** [comment]
> 下面这两个好像都行哈哈
> ![image](https://user-images.githubusercontent.com/20442232/96336252-07243000-10b1-11eb-81cf-5d90f8368cae.png)
> ![image](https://user-images.githubusercontent.com/20442232/96336255-11462e80-10b1-11eb-8023-0d027dd366ca.png)



我是V4 建议买V4 把风扇加满
推荐买 C3 xxx 的非侧透版本吗

**Comment by blueskies2099** [comment]
C3 plus 我也推荐 之前用过 就是挺大的

**Comment by tlerbao** [comment]
@josways 我没能理解你是建议我买v4加满风扇还是买c3xxx非侧透哈

**Comment by blueskies2099** [comment]
这个 v4 挺好看的 买来 把我的旧板子塞进去 做服务器 美滋滋

**Comment by josways** [comment]
> 这个 v4 挺好看的 买来 把我的旧板子塞进去 做服务器 美滋滋

铁闷罐。不加风扇等着爆炸。

**Comment by blueskies2099** [comment]
20L 我放弃了

**Comment by blueskies2099** [comment]
15L 以上 不考虑

**Comment by tlerbao** [comment]
![image](https://user-images.githubusercontent.com/20442232/96336366-d2fd3f00-10b1-11eb-91cc-0a63d403575d.png)

这个看着也不错，如果选这种侧透的，需要注意什么才能让透出来的东西不那么难看呢，我看有的人的机箱里面乱七八糟的 五颜六色的电源线啥的。

**Comment by wangqingzh** [comment]
@tlerbao 
![image](https://user-images.githubusercontent.com/32238306/96336394-0b048200-10b2-11eb-8e9a-25b249ab72f9.png)

**Comment by blueskies2099** [comment]
https://item.jd.com/10023120407599.html
这个

**Comment by blueskies2099** [comment]
21L 马马虎虎 么得侧透 抄袭版

**Comment by tlerbao** [comment]
看比赛呢，LPL一号种子TES要回家了 TMD

**Comment by blueskies2099** [comment]
大家都在看比赛。。。

**Comment by blueskies2099** [comment]
@josways 大佬 我 rx5500xt+dell 4k + dp 字体感觉不如之前的核显 有锯齿感 大佬有遇到过吗

**Comment by josways** [comment]
> @josways 大佬 我 rx5500xt+dell 4k + dp 字体感觉不如之前的核显 有锯齿感 大佬有遇到过吗

没啊 我感觉很清晰-。- 我 24寸4K 。 我很怀疑你 HIDPI 没有正常打开。

**Comment by josways** [comment]
> https://item.jd.com/10023120407599.html
> 这个

已入手

**Comment by blueskies2099** [comment]
@josways 24寸 4K,,,,那必须清晰啊，大兄弟用的哪款显示器，我当时也想买23 24寸的，没找到，，，4K分辨率hidip默认打开的吧

老哥 买机箱的速度 骚气

**Comment by tlerbao** [comment]
@josways @wangqingzh 这个机箱我的审美怎么觉得一般呢，为何你们好像很喜欢的样子

**Comment by josways** [comment]
> @josways 24寸 4K,,,,那必须清晰啊，大兄弟用的哪款显示器，我当时也想买23 24寸的，没找到，，，4K分辨率hidip默认打开的吧
> 
> 老哥 买机箱的速度 骚气

[https://item.jd.com/100003928805.html](https://item.jd.com/100003928805.html)

默认开启HIDPI
