### ISSUE TITLE
一模一样的配置，但是睡眠秒唤醒

### ISSUE THREAD

**Issue by AndroidDeals** [josways/B460M-MORTAR#13]
一模一样的配置，但是睡眠秒唤醒。听说是蓝牙问题，你们的免驱网卡都可以正常睡眠吗，求一个解决方法

**Comment by josways** [comment]
-.- 看看其他gay友有没有什么好的解决办法吧。建议直接加钱买个免驱卡

**Comment by AndroidDeals** [comment]
BCM94360CS2这个网卡就是免驱卡啊

**Comment by josways** [comment]
我个人无问题

**Comment by josways** [comment]
建议把蓝牙的线，在主板上换个USB2.0的口。

**Comment by AndroidDeals** [comment]
好奇怪哦，460迫击炮主板上就两个9针usb口，然后我都试过了。usb都是显示的是这个样子。你的能识别出来不。
<img width="898" alt="截屏2020-11-06 上午10 29 48" src="https://user-images.githubusercontent.com/34513334/98319159-185ebd80-201b-11eb-98c4-abbf3bb6799a.png">

**Comment by josways** [comment]
我主板都卖了 ， 等有空我给你找个机器看看。

**Comment by AndroidDeals** [comment]
老哥不用啦，已经解决掉了这个问题。 
``` 
免驱网卡的话，因为蓝牙模块外接9针usb 2.0 hub，所以造成无法内建蓝牙。如果BIOS开启了USB唤醒，那么睡眠肯定会被唤醒的。从BIOS里面再把USB唤醒关掉就可以正常睡眠了。但是这样睡眠如果要唤醒的话就只能按电源键了。等待问题是否会被完美解决吧。

```
这里是我机器的的EFI地址 [点击转到](https://github.com/AndroidDeals/i5-10500es-Msi-B460M-Mortar-Hackintosh)

**Comment by licoba** [comment]
> 老哥不用啦，已经解决掉了这个问题。
> 
> ```
> 免驱网卡的话，因为蓝牙模块外接9针usb 2.0 hub，所以造成无法内建蓝牙。如果BIOS开启了USB唤醒，那么睡眠肯定会被唤醒的。从BIOS里面再把USB唤醒关掉就可以正常睡眠了。但是这样睡眠如果要唤醒的话就只能按电源键了。等待问题是否会被完美解决吧。
> ```
> 
> 这里是我机器的的EFI地址 [点击转到](https://github.com/AndroidDeals/i5-10500es-Msi-B460M-Mortar-Hackintosh)

这……我把USB唤醒开启，也是得重新按电源键才能唤醒啊，没啥区别感觉

**Comment by AndroidDeals** [comment]
> > 老哥不用啦，已经解决掉了这个问题。
> > ```
> > 免驱网卡的话，因为蓝牙模块外接9针usb 2.0 hub，所以造成无法内建蓝牙。如果BIOS开启了USB唤醒，那么睡眠肯定会被唤醒的。从BIOS里面再把USB唤醒关掉就可以正常睡眠了。但是这样睡眠如果要唤醒的话就只能按电源键了。等待问题是否会被完美解决吧。
> > ```
> > 
> > 
> > 这里是我机器的的EFI地址 [点击转到](https://github.com/AndroidDeals/i5-10500es-Msi-B460M-Mortar-Hackintosh)
> 
> 这……我把USB唤醒开启，也是得重新按电源键才能唤醒啊，没啥区别感觉

你也用了这款网卡吗？

**Comment by licoba** [comment]
> > > 老哥不用啦，已经解决掉了这个问题。
> > > ```
> > > 免驱网卡的话，因为蓝牙模块外接9针usb 2.0 hub，所以造成无法内建蓝牙。如果BIOS开启了USB唤醒，那么睡眠肯定会被唤醒的。从BIOS里面再把USB唤醒关掉就可以正常睡眠了。但是这样睡眠如果要唤醒的话就只能按电源键了。等待问题是否会被完美解决吧。
> > > ```
> > > 
> > > 
> > > 这里是我机器的的EFI地址 [点击转到](https://github.com/AndroidDeals/i5-10500es-Msi-B460M-Mortar-Hackintosh)
> > 
> > 
> > 这……我把USB唤醒开启，也是得重新按电源键才能唤醒啊，没啥区别感觉
> 
> 你也用了这款网卡吗？

我用的有线网卡，主板自带的

**Comment by AndroidDeals** [comment]
秒唤醒就是因为那个博通免驱网卡蓝牙模块。你没有这个无线网卡的话，开了usb唤醒肯定没问题的。

**Comment by licoba** [comment]
> 秒唤醒就是因为那个博通免驱网卡蓝牙模块。你没有这个无线网卡的话，开了usb唤醒肯定没问题的。

我开了USB唤醒，但是还是不行，只能点亮键盘鼠标，没办法唤醒主机， issue里面好像也有人有同样的问题

**Comment by licoba** [comment]
> 秒唤醒就是因为那个博通免驱网卡蓝牙模块。你没有这个无线网卡的话，开了usb唤醒肯定没问题的。

好的，我再试试

**Comment by AndroidDeals** [comment]
> > 秒唤醒就是因为那个博通免驱网卡蓝牙模块。你没有这个无线网卡的话，开了usb唤醒肯定没问题的。
> 
> 我开了USB唤醒，但是还是不行，只能点亮键盘鼠标，没办法唤醒主机， issue里面好像也有人有同样的问题

试着定制下自己的USB
