### ISSUE TITLE
远景的原贴更新11月6日更新了一个版本

### ISSUE THREAD

**Issue by niroshea** [josways/B460M-MORTAR#14]
能否搬运一下，大佬辛苦了！

主要是我现在更换了U盘的 EFI 文件夹，启动时 卡在苹果logo上，没进度条出现。我不知道是不是因为OC 0.6.3的问题。

烧录U盘貌似用的 OC 0.6.3。

我是个小白，也没远景账号、注册码。请求老哥搬运一下，多谢！

**Comment by josways** [comment]
> 能否搬运一下，大佬辛苦了！
> 
> 主要是我现在更换了U盘的 EFI 文件夹，启动时 卡在苹果logo上，没进度条出现。我不知道是不是因为OC 0.6.3的问题。
> 
> 烧录U盘貌似用的 OC 0.6.3。
> 
> 我是个小白，也没远景账号、注册码。请求老哥搬运一下，多谢！

没找到呀

**Comment by josways** [comment]
链接：https://pan.baidu.com/s/1N5PVzuz_Ji0LYRko75WGcg 
提取码：8jo2 
复制这段内容后打开百度网盘手机App，操作更方便哦

先用着 暂时没时间更新GitHub的库

**Comment by blueskies2099** [comment]
11月6号的efi 升到了 big sur 没啥问题 奥利给

**Comment by josways** [comment]
已更新
de3fff3
