### ISSUE TITLE
哥哥，远景原帖更新12月的辽

### ISSUE THREAD

**Issue by tiancaikelisi** [josways/B460M-MORTAR#15]
rt

**Comment by josways** [comment]
没看到具体更新的项目，麻烦提供一下楼层可以吗？

**Comment by tiancaikelisi** [comment]
就在楼顶能看


2020年12月7日小更新一下核显部分代码，适配最新版whatevergreen，实测fcpx预览更流畅（big
sur系统也已经测试没问题了）,同时更新所有插件到最新版  oc0.6.3-2020-12-7.zip
<http://bbs.pcbeta.com/forum.php?mod=attachment&aid=NDI1MDMxOXwzYTAyN2RiZHwxNjA4OTEyNDY3fDQ4NzY4ODF8MTg2MTQ3Mg%3D%3D>
 (2.25 MB, 下载次数: 111)

在 2020年12月25日週五 18:10，Josway <notifications@github.com> 寫道：

**Comment by josways** [comment]
已更新
de3fff3
