### ISSUE TITLE
请问网卡使用的什么型号

### ISSUE THREAD

**Issue by AmbitiondX** [josways/B460M-MORTAR#2]
请问网卡使用的什么型号

**Comment by josways** [comment]
一切拆机卡/免驱卡都可以，转pcie。
我自己用的 BCM94360CS2

**Comment by include041236** [comment]
请问有线网卡是否正常工作

**Comment by josways** [comment]
看 readme

**Comment by johnyang007** [comment]
BCM94360CS2 我也是这款。无线没问题，蓝牙好像打不开。

**Comment by josways** [comment]
> BCM94360CS2 我也是这款。无线没问题，蓝牙好像打不开。

查看原帖的USB端口配置，或者直接把无线网卡的USB接口换个位置

**Comment by johnyang007** [comment]
> > BCM94360CS2 我也是这款。无线没问题，蓝牙好像打不开。
> 
> 查看原帖的USB端口配置，或者直接把无线网卡的USB接口换个位置

我大概知道了，我的是B460M WIFI版本。网卡是94360CS2是NGFF转接的，没有外置的USB接口，无法换位置。应该是USB的端口定制对不上，我看你是USB定制对到了HS11上，我得研究一下这个NGFF接口的怎么定制USB

**Comment by johnyang007** [comment]
还有就是，兄弟。这个10.15.6当前B460M的USB定制流程大题可以发一下吗，我搜索网上教程有点乱，不知道照着哪个来。

**Comment by josways** [comment]
> > > BCM94360CS2 我也是这款。无线没问题，蓝牙好像打不开。
> > 
> > 
> > 查看原帖的USB端口配置，或者直接把无线网卡的USB接口换个位置
> 
> 我大概知道了，我的是B460M WIFI版本。网卡是94360CS2是NGFF转接的，没有外置的USB接口，无法换位置。应该是USB的端口定制对不上，我看你是USB定制对到了HS11上，我得研究一下这个NGFF接口的怎么定制USB

[https://blog.daliansky.net/Intel-FB-Patcher-USB-Custom-Video.html](https://blog.daliansky.net/Intel-FB-Patcher-USB-Custom-Video.html)

**Comment by johnyang007** [comment]
多谢，已经通过USB定制识别蓝牙了。

**Comment by Turhapuro** [comment]
I am also stuck in MSI B460M WIFI mobo missing Bluetooth. Wifi works well.
 johnyang007 could you share your EFI, so I could get Bluetooth to work?

**Comment by johnyang007** [comment]
> I am also stuck in MSI B460M WIFI mobo missing Bluetooth. Wifi works well.
> johnyang007 could you share your EFI, so I could get Bluetooth to work?

I am upload my EFI.
link: https://github.com/johnyang007/b460m-martor-wifi
