### ISSUE TITLE
请问是否有核显的版本

### ISSUE THREAD

**Issue by gtr2003** [josways/B460M-MORTAR#4]
请问是否有核显的版本
黑苹果下的RX570非常耗电，双屏幕下待机都50~60瓦
希望有只有核显的EFI版本

**Comment by josways** [comment]
自己跟着这个帖子动手改
http://bbs.pcbeta.com/viewthread-1861919-1-7.html

**Comment by josways** [comment]
已有核显配置文件 `/EFI/OC/Config-集成显卡专用-主板dp接口.plist`
de3fff3

**Comment by josways** [comment]
Config-集成显卡专用-主板dp接口.plist
