### ISSUE TITLE
插入U盘，正常进入，进度条走到一半黑屏

### ISSUE THREAD

**Issue by beyondskyway** [josways/B460M-MORTAR#6]
1、处理器 i7 10700k，显卡蓝宝石5500XT
2、使用的黑果小兵的镜像：https://blog.daliansky.net/macOS-Catalina-10.15.5-19F96-Release-version-with-Clover-5118-original-image-Double-EFI-Version-UEFI-and-MBR.html
3、然后通过balenaEtcher刷到U盘
4、从U盘启动，选择安装macos，然后走进度条，走到一半停住一会，就黑屏一直无反应了

**Comment by josways** [comment]
xt显卡需要额外加 启动参数: `agdpmod=pikera`

**Comment by josways** [comment]
更新了 
de3fff3
现在可以再次尝试一下.
配置选择 `EFI/OC/Config-RX5500-RX5600显卡用.plist`
