### ISSUE TITLE
您好大佬，相同配置，机箱背部扬声器没有声音，休眠/唤醒黑屏

### ISSUE THREAD

**Issue by sanhaowuai** [josways/B460M-MORTAR#8]
相同配置，有如下两个问题：
1.机箱背部扬声器没有声音，耳机插口没问题有声音
2.休眠/唤醒黑屏，只能重启，网上说得关闭串行端口，但是我没有在主板上找到这个设置，请大佬帮忙解答，谢谢！！！

**Comment by josways** [comment]
建议自己排查

**Comment by josways** [comment]
已更新版本,建议再次尝试一下.

**Comment by licoba** [comment]
> 相同配置，有如下两个问题：
> 1.机箱背部扬声器没有声音，耳机插口没问题有声音
> 2.休眠/唤醒黑屏，只能重启，网上说得关闭串行端口，但是我没有在主板上找到这个设置，请大佬帮忙解答，谢谢！！！

我也有这两个问题，请问搂着你解决了吗

**Comment by josways** [comment]
已再次更新版本 建议再次尝试一下.
de3fff3
